import { PcmWindowMeter } from "../apps/web/src/pcmWindow.ts";
import type { AudioMeasurementEvent } from "../apps/web/src/audioMeasurement.ts";
import type { PcmEvidence, PcmPlayback } from "../packages/experiments/pcm.ts";

/** Offline synthetic metadata generated by the actual window meter; no fixture audio is stored. */
export function pcmEvidence(options: {
  durationMs?: number;
  meterOriginSeconds?: number;
  performanceOriginMs?: number;
  input?: readonly (readonly [number, number])[];
  output?: readonly (readonly [number, number])[];
  playbacks?: PcmPlayback[];
  gaps?: readonly { atMs: number; durationMs: number }[];
} = {}): PcmEvidence {
  const durationMs = options.durationMs ?? 3000;
  const origin = options.meterOriginSeconds ?? 50;
  const performanceOrigin = options.performanceOriginMs ?? 1000;
  const sampleRate = 8000;
  const events: AudioMeasurementEvent[] = [
    { version: 1, measurementId: "test-meter", type: "anchor", sampleRate, windowMs: 20,
      thresholdDbfs: -45, activeWindows: 3, silentWindows: 6,
      clockAnchor: { contextTime: origin, performanceNowMs: performanceOrigin } },
    { version: 1, measurementId: "test-meter", type: "status", status: "measuring",
      clockAnchor: { contextTime: origin, performanceNowMs: performanceOrigin } },
  ];
  const input = options.input ?? [[0.1, 0.4], [1.1, 1.4]];
  const output = options.output ?? [[0.8, 1.5]];
  const meters = [new PcmWindowMeter(sampleRate, "input"), new PcmWindowMeter(sampleRate, "output")];
  let nextGap = 0;
  for (let windowStartMs = 0; windowStartMs + 20 <= durationMs; windowStartMs += 20) {
    const gap = options.gaps?.[nextGap];
    if (gap && windowStartMs >= gap.atMs) {
      windowStartMs += gap.durationMs;
      nextGap += 1;
      meters.forEach((meter) => meter.reset());
      for (const status of ["paused", "measuring"] as const) events.push({
        version: 1, measurementId: "test-meter", type: "status", status,
        clockAnchor: { contextTime: origin + windowStartMs / 1000, performanceNowMs: performanceOrigin + windowStartMs },
      });
    }
    if (windowStartMs + 20 > durationMs) break;
    const begin = windowStartMs / 1000;
    const end = begin + 0.02;
    meters.forEach((meter, index) => {
      const ranges = index === 0 ? input : output;
      const active = ranges.some(([start, stop]) => begin + 0.01 >= start && begin + 0.01 < stop);
      meter.process([new Float32Array(160).fill(active ? 0.1 : 0)], Math.round((origin + begin) * sampleRate), 160, (sample) => {
        events.push({
          version: 1, measurementId: "test-meter", type: "sample", ...sample,
          clockAnchor: { contextTime: origin + end + 0.002, performanceNowMs: performanceOrigin + end * 1000 + 2 },
        });
      });
    });
  }
  const playbacks = options.playbacks ?? [
    { id: "initial", performanceStartMs: performanceOrigin, durationMs: 500, endedObservedPerformanceMs: performanceOrigin + 510 },
    { id: "second", performanceStartMs: performanceOrigin + 1000, durationMs: 500, endedObservedPerformanceMs: performanceOrigin + 1510 },
  ];
  return {
    version: 1, capturedAtPerformanceMs: Math.max(performanceOrigin + Math.ceil(durationMs / 20) * 20 + 2,
      events.at(-1)?.clockAnchor.performanceNowMs ?? 0),
    events, playbacks, peers: playbacks.map((entry) => ({
      performanceNowMs: entry.performanceStartMs, connectionState: "connected", trackEnabled: true, trackReadyState: "live",
    })),
    receivedMeasurementEvents: events.length, invalidMeasurementEvents: 0, collectionGaps: 0, helperErrorCount: 0, transcriptEventCount: 0,
  };
}
